export const players = [
  {
    name: "Lionel Messi",
    country: "Argentina",
    goals: 672,
    trophies: 34,
    netWorth: "$400 million",
  },
  {
    name: "Cristiano Ronaldo",
    country: "Portugal",
    goals: 674,
    trophies: 32,
    netWorth: "$500 million",
  },
  {
    name: "Neymar Jr.",
    country: "Brazil",
    goals: 268,
    trophies: 15,
    netWorth: "$200 million",
  },
  {
    name: "Kylian Mbappé",
    country: "France",
    goals: 141,
    trophies: 10,
    netWorth: "$250 million",
  },
  {
    name: "Robert Lewandowski",
    country: "Poland",
    goals: 301,
    trophies: 23,
    netWorth: "$120 million",
  },
  {
    name: "Kevin De Bruyne",
    country: "Belgium",
    goals: 128,
    trophies: 14,
    netWorth: "$150 million",
  },
  {
    name: "Sergio Ramos",
    country: "Spain",
    goals: 101,
    trophies: 27,
    netWorth: "$80 million",
  },
  {
    name: "Mohamed Salah",
    country: "Egypt",
    goals: 135,
    trophies: 13,
    netWorth: "$90 million",
  },
  {
    name: "Harry Kane",
    country: "England",
    goals: 221,
    trophies: 2,
    netWorth: "$120 million",
  },
  {
    name: "Manuel Neuer",
    country: "Germany",
    goals: 0,
    trophies: 31,
    netWorth: "$75 million",
  },
  {
    name: "Virgil van Dijk",
    country: "Netherlands",
    goals: 39,
    trophies: 12,
    netWorth: "$90 million",
  },
  {
    name: "Sadio Mané",
    country: "Senegal",
    goals: 130,
    trophies: 10,
    netWorth: "$60 million",
  },
  {
    name: "Gareth Bale",
    country: "Wales",
    goals: 221,
    trophies: 16,
    netWorth: "$90 million",
  },
  {
    name: "Eden Hazard",
    country: "Belgium",
    goals: 119,
    trophies: 10,
    netWorth: "$100 million",
  },
  {
    name: "Paul Pogba",
    country: "France",
    goals: 78,
    trophies: 15,
    netWorth: "$85 million",
  },
  {
    name: "Antoine Griezmann",
    country: "France",
    goals: 195,
    trophies: 12,
    netWorth: "$95 million",
  },
  {
    name: "Luis Suárez",
    country: "Uruguay",
    goals: 323,
    trophies: 15,
    netWorth: "$70 million",
  },
  {
    name: "Toni Kroos",
    country: "Germany",
    goals: 64,
    trophies: 28,
    netWorth: "$60 million",
  },
  {
    name: "Romelu Lukaku",
    country: "Belgium",
    goals: 237,
    trophies: 7,
    netWorth: "$100 million",
  },
  {
    name: "Pierre-Emerick Aubameyang",
    country: "Gabon",
    goals: 233,
    trophies: 4,
    netWorth: "$75 million",
  },
  {
    name: "Erling Haaland",
    country: "Norway",
    goals: 92,
    trophies: 2,
    netWorth: "$100 million",
  },
  {
    name: "Bruno Fernandes",
    country: "Portugal",
    goals: 73,
    trophies: 4,
    netWorth: "$80 million",
  },
  {
    name: "Jadon Sancho",
    country: "England",
    goals: 49,
    trophies: 2,
    netWorth: "$70 million",
  },
  {
    name: "Harry Maguire",
    country: "England",
    goals: 12,
    trophies: 4,
    netWorth: "$80 million",
  },
  {
    name: "Raheem Sterling",
    country: "England",
    goals: 125,
    trophies: 11,
    netWorth: "$90 million",
  },
  {
    name: "Marcus Rashford",
    country: "England",
    goals: 96,
    trophies: 5,
    netWorth: "$80 million",
  },
  {
    name: "Alphonso Davies",
    country: "Canada",
    goals: 8,
    trophies: 9,
    netWorth: "$60 million",
  },
  {
    name: "Joshua Kimmich",
    country: "Germany",
    goals: 37,
    trophies: 18,
    netWorth: "$80 million",
  },
  {
    name: "Karim Benzema",
    country: "France",
    goals: 287,
    trophies: 24,
    netWorth: "$70 million",
  },
  {
    name: "Edinson Cavani",
    country: "Uruguay",
    goals: 268,
    trophies: 15,
    netWorth: "$50 million",
  },
  {
    name: "N'Golo Kanté",
    country: "France",
    goals: 23,
    trophies: 16,
    netWorth: "$60 million",
  },
  {
    name: "Thomas Müller",
    country: "Germany",
    goals: 227,
    trophies: 32,
    netWorth: "$60 million",
  },
  {
    name: "Son Heung-min",
    country: "South Korea",
    goals: 141,
    trophies: 5,
    netWorth: "$80 million",
  },
  {
    name: "Trent Alexander-Arnold",
    country: "England",
    goals: 13,
    trophies: 9,
    netWorth: "$60 million",
  },
  {
    name: "Hakim Ziyech",
    country: "Morocco",
    goals: 78,
    trophies: 9,
    netWorth: "$50 million",
  },
  {
    name: "Thiago Alcantara",
    country: "Spain",
    goals: 32,
    trophies: 18,
    netWorth: "$60 million",
  },
  {
    name: "Lautaro Martínez",
    country: "Argentina",
    goals: 56,
    trophies: 2,
    netWorth: "$70 million",
  },
  {
    name: "Frenkie de Jong",
    country: "Netherlands",
    goals: 19,
    trophies: 10,
    netWorth: "$60 million",
  },
  {
    name: "Marquinhos",
    country: "Brazil",
    goals: 25,
    trophies: 25,
    netWorth: "$50 million",
  },
  {
    name: "Gianluigi Donnarumma",
    country: "Italy",
    goals: 0,
    trophies: 5,
    netWorth: "$40 million",
  },
  {
    name: "Jamie Vardy",
    country: "England",
    goals: 138,
    trophies: 2,
    netWorth: "$40 million",
  },
  {
    name: "Kalidou Koulibaly",
    country: "Senegal",
    goals: 9,
    trophies: 0,
    netWorth: "$50 million",
  },
  {
    name: "Ciro Immobile",
    country: "Italy",
    goals: 229,
    trophies: 6,
    netWorth: "$30 million",
  },
  {
    name: "Keylor Navas",
    country: "Costa Rica",
    goals: 0,
    trophies: 23,
    netWorth: "$20 million",
  },
  {
    name: "Andrew Robertson",
    country: "Scotland",
    goals: 7,
    trophies: 18,
    netWorth: "$40 million",
  },
  {
    name: "Rodri",
    country: "Spain",
    goals: 14,
    trophies: 7,
    netWorth: "$50 million",
  },
  {
    name: "Serge Gnabry",
    country: "Germany",
    goals: 64,
    trophies: 9,
    netWorth: "$40 million",
  },
  {
    name: "Lucas Moura",
    country: "Brazil",
    goals: 96,
    trophies: 8,
    netWorth: "$30 million",
  },
  {
    name: "Memphis Depay",
    country: "Netherlands",
    goals: 124,
    trophies: 6,
    netWorth: "$30 million",
  },
  {
    name: "Gerard Piqué",
    country: "Spain",
    goals: 52,
    trophies: 34,
    netWorth: "$50 million",
  },
  {
    name: "Jude Bellingham",
    country: "England",
    goals: 10,
    trophies: 1,
    netWorth: "$30 million",
  },
  {
    name: "Giovanni Reyna",
    country: "United States",
    goals: 18,
    trophies: 0,
    netWorth: "$40 million",
  },
  {
    name: "Nicolo Barella",
    country: "Italy",
    goals: 21,
    trophies: 4,
    netWorth: "$30 million",
  },
  {
    name: "Kai Havertz",
    country: "Germany",
    goals: 36,
    trophies: 2,
    netWorth: "$70 million",
  },
  {
    name: "João Félix",
    country: "Portugal",
    goals: 32,
    trophies: 4,
    netWorth: "$80 million",
  },
  {
    name: "Declan Rice",
    country: "England",
    goals: 9,
    trophies: 0,
    netWorth: "$60 million",
  },
  {
    name: "Pedri",
    country: "Spain",
    goals: 10,
    trophies: 1,
    netWorth: "$50 million",
  },
  {
    name: "Eduardo Camavinga",
    country: "France",
    goals: 6,
    trophies: 1,
    netWorth: "$40 million",
  },
  {
    name: "Ansu Fati",
    country: "Spain",
    goals: 13,
    trophies: 4,
    netWorth: "$60 million",
  },
  {
    name: "Timo Werner",
    country: "Germany",
    goals: 118,
    trophies: 5,
    netWorth: "$70 million",
  },
  {
    name: "Sergej Milinković-Savić",
    country: "Serbia",
    goals: 58,
    trophies: 5,
    netWorth: "$40 million",
  },
  {
    name: "Matthijs de Ligt",
    country: "Netherlands",
    goals: 10,
    trophies: 8,
    netWorth: "$50 million",
  },
  {
    name: "Rodrygo",
    country: "Brazil",
    goals: 21,
    trophies: 6,
    netWorth: "$40 million",
  },
  {
    name: "Aaron Wan-Bissaka",
    country: "England",
    goals: 2,
    trophies: 6,
    netWorth: "$40 million",
  },
  {
    name: "Renato Sanches",
    country: "Portugal",
    goals: 22,
    trophies: 6,
    netWorth: "$30 million",
  },
  {
    name: "Marcel Sabitzer",
    country: "Austria",
    goals: 65,
    trophies: 4,
    netWorth: "$40 million",
  },
  {
    name: "Raphael Varane",
    country: "France",
    goals: 19,
    trophies: 19,
    netWorth: "$50 million",
  },
  {
    name: "Dani Olmo",
    country: "Spain",
    goals: 25,
    trophies: 5,
    netWorth: "$40 million",
  },
  {
    name: "Houssem Aouar",
    country: "France",
    goals: 32,
    trophies: 2,
    netWorth: "$50 million",
  },
  {
    name: "Gianluigi Buffon",
    country: "Italy",
    goals: 0,
    trophies: 28,
    netWorth: "$10 million",
  },
  {
    name: "Jack Grealish",
    country: "England",
    goals: 44,
    trophies: 0,
    netWorth: "$70 million",
  },
  {
    name: "Lucas Paquetá",
    country: "Brazil",
    goals: 28,
    trophies: 4,
    netWorth: "$30 million",
  },
  {
    name: "Federico Chiesa",
    country: "Italy",
    goals: 29,
    trophies: 3,
    netWorth: "$50 million",
  },
  {
    name: "Ryan Gravenberch",
    country: "Netherlands",
    goals: 14,
    trophies: 1,
    netWorth: "$40 million",
  },
  {
    name: "Eduardo Salvio",
    country: "Argentina",
    goals: 46,
    trophies: 13,
    netWorth: "$30 million",
  },
  {
    name: "Mason Mount",
    country: "England",
    goals: 30,
    trophies: 2,
    netWorth: "$60 million",
  },
  {
    name: "André Silva",
    country: "Portugal",
    goals: 112,
    trophies: 2,
    netWorth: "$50 million",
  },
  {
    name: "Federico Valverde",
    country: "Uruguay",
    goals: 20,
    trophies: 5,
    netWorth: "$40 million",
  },
  {
    name: "Lorenzo Pellegrini",
    country: "Italy",
    goals: 33,
    trophies: 1,
    netWorth: "$30 million",
  },
  {
    name: "Victor Osimhen",
    country: "Nigeria",
    goals: 36,
    trophies: 2,
    netWorth: "$50 million",
  },
  {
    name: "Leon Goretzka",
    country: "Germany",
    goals: 47,
    trophies: 15,
    netWorth: "$40 million",
  },
  {
    name: "Dominik Szoboszlai",
    country: "Hungary",
    goals: 18,
    trophies: 4,
    netWorth: "$30 million",
  },
  {
    name: "Piotr Zieliński",
    country: "Poland",
    goals: 39,
    trophies: 5,
    netWorth: "$30 million",
  },
  {
    name: "Donyell Malen",
    country: "Netherlands",
    goals: 52,
    trophies: 4,
    netWorth: "$40 million",
  },
  {
    name: "Phil Foden",
    country: "England",
    goals: 30,
    trophies: 8,
    netWorth: "$60 million",
  },
  {
    name: "Ozan Kabak",
    country: "Turkey",
    goals: 5,
    trophies: 1,
    netWorth: "$40 million",
  },
  {
    name: "Dayot Upamecano",
    country: "France",
    goals: 7,
    trophies: 2,
    netWorth: "$50 million",
  },
  {
    name: "Ryan Sessegnon",
    country: "England",
    goals: 9,
    trophies: 1,
    netWorth: "$40 million",
  },
  {
    name: "José Giménez",
    country: "Uruguay",
    goals: 11,
    trophies: 8,
    netWorth: "$40 million",
  },
  {
    name: "Leon Bailey",
    country: "Jamaica",
    goals: 48,
    trophies: 2,
    netWorth: "$30 million",
  },
  {
    name: "Matheus Cunha",
    country: "Brazil",
    goals: 34,
    trophies: 4,
    netWorth: "$30 million",
  },
  {
    name: "Odsonne Édouard",
    country: "France",
    goals: 59,
    trophies: 12,
    netWorth: "$30 million",
  },
  {
    name: "Evan N'Dicka",
    country: "France",
    goals: 3,
    trophies: 1,
    netWorth: "$40 million",
  },
  {
    name: "Matías Vecino",
    country: "Uruguay",
    goals: 32,
    trophies: 6,
    netWorth: "$30 million",
  },
  {
    name: "Alex Telles",
    country: "Brazil",
    goals: 26,
    trophies: 14,
    netWorth: "$30 million",
  },
  {
    name: "Emerson Palmieri",
    country: "Italy",
    goals: 15,
    trophies: 11,
    netWorth: "$30 million",
  },
  {
    name: "Matteo Guendouzi",
    country: "France",
    goals: 10,
    trophies: 1,
    netWorth: "$40 million",
  },
  {
    name: "Pedro Neto",
    country: "Portugal",
    goals: 17,
    trophies: 0,
    netWorth: "$40 million",
  },
  {
    name: "Florentino Luís",
    country: "Portugal",
    goals: 3,
    trophies: 1,
    netWorth: "$40 million",
  },
  {
    name: "Gianluca Mancini",
    country: "Italy",
    goals: 12,
    trophies: 1,
    netWorth: "$30 million",
  },
  {
    name: "Davide Calabria",
    country: "Italy",
    goals: 6,
    trophies: 4,
    netWorth: "$30 million",
  },
  {
    name: "Dani Ceballos",
    country: "Spain",
    goals: 16,
    trophies: 5,
    netWorth: "$30 million",
  },
  {
    name: "Jean-Philippe Mateta",
    country: "France",
    goals: 29,
    trophies: 0,
    netWorth: "$30 million",
  },
  {
    name: "Darío Benedetto",
    country: "Argentina",
    goals: 103,
    trophies: 8,
    netWorth: "$30 million",
  },
  {
    name: "Robin Gosens",
    country: "Germany",
    goals: 25,
    trophies: 2,
    netWorth: "$30 million",
  },
  {
    name: "Mikel Oyarzabal",
    country: "Spain",
    goals: 77,
    trophies: 2,
    netWorth: "$30 million",
  },
  {
    name: "Matheus Pereira",
    country: "Brazil",
    goals: 35,
    trophies: 0,
    netWorth: "$30 million",
  },
  {
    name: "Leonardo Balerdi",
    country: "Argentina",
    goals: 4,
    trophies: 1,
    netWorth: "$30 million",
  },
];
